# References:
# https://github.com/GoogleCloudPlatform/gke-gitops-tutorial-cloudbuild/blob/master/cloudbuild-trigger-cd.yaml
# https://github.com/PimDeWitte/UnityAutoIncrementBuildVersion/issues/1

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=id_rsa.enc
      - --plaintext-file=/root/.ssh/id_rsa
      - --location=global
      - --keyring=private-keys
      - --key=github-key
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    id: 'id_rsa'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        mv known_hosts /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    id: 'known_hosts'
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/Adimpression/Dimensions.git']
    id: 'repo-Dimensions'
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/Adimpression/Scarcity.git']
    id: 'repo-Scarcity'
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'git@github.com:Adimpression/proto.git']
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    waitFor:
      - 'id_rsa'
      - 'known_hosts'
    id: 'repo-proto'
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['-Darguments', '-Dmaven.javadoc.skip=true', '-DskipTests=true','-f','Scarcity/pom.xml', 'clean', 'install']
    waitFor:
      - 'repo-Scarcity'
      - 'repo-Dimensions'
      - 'repo-proto'
    id: 'mvn'
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./Scarcity/generator/src/main/proto", "gs://dimensions.x.qs.fyi/"]
    waitFor:
      - 'mvn'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp -r ./Scarcity/generator/target/generated-sources/protobuf/java/ ./proto/
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    waitFor:
      - 'mvn'
    id: 'cp-proto'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -x && \
        cd proto && \
        git add * && \
        git commit -m "Generated proto from commit ${COMMIT_SHA}" && \
        git push origin master
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    waitFor:
      - 'cp-proto'
    id: 'commit-proto'