# References:
# https://github.com/GoogleCloudPlatform/gke-gitops-tutorial-cloudbuild/blob/master/cloudbuild-trigger-cd.yaml
# https://github.com/PimDeWitte/UnityAutoIncrementBuildVersion/issues/1

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=id_rsa.enc
      - --plaintext-file=/root/.ssh/id_rsa
      - --location=global
      - --keyring=private-keys
      - --key=github-key
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    id: 'id_rsa'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        mv known_hosts /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    id: 'known_hosts'
  - name: gcr.io/cloud-builders/git
    args: ['clone', '--recurse-submodules', 'https://github.com/Adimpression/Dimensions.git']
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    waitFor:
      - 'id_rsa'
      - 'known_hosts'
    id: 'repo-Dimensions'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd Dimensions && \
        git submodule init && \
        git submodule update
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/Adimpression/Scarcity.git']
    id: 'repo-Scarcity'
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'git@github.com:Adimpression/proto.git']
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    waitFor:
      - 'id_rsa'
      - 'known_hosts'
    id: 'repo-proto'
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['-Darguments', '-Dmaven.javadoc.skip=true', '-DskipTests=true','-f','Scarcity/pom.xml', 'release:clean', 'release:prepare', 'release:perform']
    waitFor:
      - 'repo-Scarcity'
      - 'repo-Dimensions'
      - 'repo-proto'
    id: 'mvn'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        rm -rf ./proto/proto/ && \
        cp -Rv ./Scarcity/generator/src/main/proto/* ./proto/
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    waitFor:
      - 'mvn'
    id: 'cp-proto'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd ./proto && \
        git config --global user.email "talktome@adimpression.mobi" && \
        git config --global user.name "Adimpression" && \
        git add -A && git commit -a -m "Generated proto from commit ${COMMIT_SHA}" && \
        git push origin master
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    waitFor:
      - 'cp-proto'
    id: 'commit-proto'