steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/Adimpression/Dimensions.git']
    id: 'repo-Dimensions'
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/Adimpression/Scarcity.git']
    id: 'repo-Scarcity'
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['-Darguments', '-Dmaven.javadoc.skip=true', '-DskipTests=true','-f','Scarcity/pom.xml', 'clean', 'install']
    waitFor:
      - 'repo-Scarcity'
      - 'repo-Dimensions'
    id: 'mvn'
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./Scarcity/generator/src/main/proto", "gs://dimensions.x.qs.fyi/"]
    waitFor:
      - 'mvn'